# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    command: pipenv run start
    ports:
      - '8000:8000'
    links:
      - mongo
      - mongo-express
      - redis
    environment:
      LANG: 'en_US.UTF-8'
      LC_ALL: 'en_US.UTF-8'
      REDIS_HOST: 'redis'
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    command: [--auth]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    command: [redis-server, --loglevel, notice]
    volumes:
      - redis:/data/redis

volumes:
  mongo: {}
  redis: {}
